[package]
name = "kb-remap"
version = "0.0.1"
authors = ["Ross MacArthur <ross@macarthur.io>"]
edition = "2018"
description = "Tool to assist remapping macOS keyboard keys"
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/rossmacarthur/kb-remap"
keywords = ["keyboard", "macos"]
categories = ["command-line-utilities"]

[dependencies]
anyhow = "1.0.38"
clap = "3.0.0-beta.2"
itertools = "0.10.0"
regex-macro = "0.1.1"
serde = { version = "1.0.124", features = ["derive"] }
serde_json = "1.0.64"
thiserror = "1.0.24"
